### ISSUE TITLE
TBI-Add Coverage report

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#11]
### Description

Add coverage report - check https://coveralls.io/

---

### Notes
Assumptions / Links / Reference

--- 

### Tasks
- [ ] Check https://coveralls.io/ if it work with jest and supertest
- [ ] Add coverage report
- [ ] Update main readme with tile?
- [ ] Set threshold?
