### ISSUE TITLE
TBI-Setup Server to start & shutdown gracefully

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#12]
### Description

Setup Server to shutdown gracefully

---

### Notes
Assumptions / Links / Reference

--- 

### Tasks
- [x] Update server startup 
- [x] Update server shutdown - look for Signals
- [x] Add HTTP Logging to server (aka morgan)
- [x] Add Configuration to server

**Comment by markmcsherry** [comment]
Separated out routes into multiple files & update integration tests

**Comment by markmcsherry** [comment]
Should add logging to application in addition to morgan http logging - should also consider writing out to file

**Comment by markmcsherry** [comment]
DOne - Closing
