### ISSUE TITLE
US-Serve initial static resources 

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#18]
**As a _persona_ I want to _do something_ so that I can _achieve some benefit_**

### Description

Use serve-static express middleware to serve favicon, logo and basic html page
---

### Notes
Assumptions / Links / Reference
http://expressjs.com/en/resources/middleware/serve-static.html
--- 

### Tasks
- [ ] Add folder structure for static resources with favicon, logo and basic html file (landing page)
- [ ] Add serve-static express middleware to project & configure to serve static resources
- [ ] Add Integration tests for static resources
