### ISSUE TITLE
TBI-Add basic Travis Build

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#2]
### Description

Add basic travis node build so for PR's

---

### Notes
Assumptions / Links / Reference

--- 

### Tasks
- [x] Add basic node .travis.yml file 
- [x] Test build is running on PR's
- [x] Add travis badge to readme

---

**Comment by markmcsherry** [comment]
Done-closing
