### ISSUE TITLE
TBI-Setup basic server

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#4]
### Description

Setup basic express server

---

### Notes
Assumptions / Links / Reference

--- 

### Tasks
- [x] Add directory structure for server module
- [x] Add package.json for server
- [x] Add server.js with basic express app
- [x] test server basid start and serve
- [x] update startup scripts in main package.json

---

**Comment by markmcsherry** [comment]
Done-closing
