### ISSUE TITLE
TBI-Add Integration test

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/lattice-core#9]
### Description

Add Integration test

---

### Notes
Assumptions / Links / Reference

--- 

### Tasks
- [x] Add jest integration test using supertest to test express
- [x] Breakout server to separate routes from startup
- [x] Add temp API route to server with test results 200 & 404
- [x] Create some integration tests based on routes in server

**Comment by markmcsherry** [comment]
Closing-done
